- name: download wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    force_basic_auth: yes
    mode: 0755

- name: Reset wordpress directory
  file:
    path: /var/www/html/wordpress
    state: absent

- name: Create wordpress directory
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: "{{ ssh_user }}"
    group: www-data
    mode: 0755

- name: Wordpress Core Download
  become: yes
  become_user: "{{ ssh_user }}"
  command: "wp core download --path=/var/www/html/wordpress"

- name: Wordpress Configuration
  become: yes
  become_user: "{{ ssh_user }}"
  command: "wp core config --dbname={{ wp_db_name }} --dbuser={{ wp_db_user }} --dbpass={{ wp_db_password }} --dbprefix={{ wp_db_prefix }} --path=/var/www/html/wordpress"

- name: Wordpress Core Install
  become: yes
  become_user: "{{ ssh_user }}"
  command: "wp core install --url='http://{{ host_name }}' --title='{{ wp_title }}' --admin_user='{{ wp_admin_user }}' --admin_password='{{ wp_admin_password }}' --admin_email='{{ wp_admin_email }}' --path=/var/www/html/wordpress"

- name: Change ownership of directory
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    mode: 0755
    state: directory
    recurse: yes
